In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error

df = pd.read_csv('../data/raw/financial_data_raw.csv')

df.drop(['Type', 'Product', 'Completed Date'], axis=1, inplace=True)

df['Date'] = pd.to_datetime(df['Started Date']).dt.normalize()
df.drop('Started Date', axis=1, inplace=True)

df = df[df['State'] != 'REVERTED']

df = df.drop(['State', 'Currency', 'Description'], axis=1)

df.head()

,Description,Amount,Fee,Currency,State,Balance,Date
0,Transfer from VINH LE TRUONG NGUYEN,100.00,0.0,EUR,COMPLETED,100.00,2024-06-02
1,Transfer from KEVIN LE NGUYEN,100.00,0.0,EUR,COMPLETED,200.00,2024-06-05
2,Transfer from KEVIN LE NGUYEN,400.00,0.0,EUR,COMPLETED,600.00,2024-06-20
3,To Kevin Nguyen,-111.81,0.0,EUR,COMPLETED,488.19,2024-06-23
4,Payment from VINH LE TRUONG NGUYEN,1448.85,0.0,EUR,COMPLETED,1937.04,2024-06-26

In [ ]:
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.weekday
df['Month'] = df['Date'].dt.month
df['Days_since_start'] = (df['Date'] - df['Date'].min()).dt.days

X = df[['Days_since_start', 'Day', 'Weekday', 'Month']]
y = df['Balance']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.weekday
df['Month'] = df['Date'].dt.month
df['Days_since_start'] = (df['Date'] - df['Date'].min()).dt.days

X = df[['Days_since_start', 'Day', 'Weekday', 'Month']]
y = df['Balance']

,Description,Amount,Fee,Currency,State,Balance,Date,Day,Weekday,Month,Days_since_start
0,Transfer from VINH LE TRUONG NGUYEN,100.00,0.0,EUR,COMPLETED,100.00,2024-06-02,2,6,6,0
1,Transfer from KEVIN LE NGUYEN,100.00,0.0,EUR,COMPLETED,200.00,2024-06-05,5,2,6,3
2,Transfer from KEVIN LE NGUYEN,400.00,0.0,EUR,COMPLETED,600.00,2024-06-20,20,3,6,18
3,To Kevin Nguyen,-111.81,0.0,EUR,COMPLETED,488.19,2024-06-23,23,6,6,21
4,Payment from VINH LE TRUONG NGUYEN,1448.85,0.0,EUR,COMPLETED,1937.04,2024-06-26,26,2,6,24

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(
    n_estimators=100, 
    max_depth=4, 
    min_samples_leaf=3,
    random_state=42,
    max_features='sqrt'
)

model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)


print(model.predict([[200, 15, 2, 6]]))